apiVersion: v1
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
kind: Secret
metadata:
  name: {{ .Values.imagepullCredentials.secretName }}
  namespace: {{ .Values.resources.namespace }}
  labels:
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
type: kubernetes.io/dockerconfigjson

