apiVersion: v1
data:
  password: {{ .Values.innodb.rootUser.password | b64enc }}
kind: Secret
metadata:
  name: {{ .Values.innodb.rootUser.secretName }}
  namespace: {{ .Values.resources.namespace }}
  labels:
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
type: Opaque

