apiVersion: v1
kind: ServiceAccount
metadata:
  name: mysql-operator
  namespace: {{ if and (.Values.operator.global) (eq .Values.resources.namespace "mysql-operator") }}mysql-operator{{ else }}{{ .Values.resources.namespace }}{{ end }}
  labels:
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
imagePullSecrets:
- name: {{ .Values.imagepullCredentials.secretName }}

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: mysql-agent
  namespace: {{ if and (.Values.operator.global) (eq .Values.resources.namespace "mysql-operator") }}default{{ else }}{{ .Values.resources.namespace }}{{ end }}
  labels:
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
imagePullSecrets:
- name: {{ .Values.imagepullCredentials.secretName }}

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.resources.rbacName }}
  namespace: {{ if and (.Values.operator.global) (eq .Values.resources.namespace "mysql-operator") }}default{{ else }}{{ .Values.resources.namespace}}{{ end }}
  labels:
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
imagePullSecrets:
- name: {{ .Values.imagepullCredentials.secretName }}


---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: {{ if and (.Values.operator.global) (eq .Values.resources.namespace "mysql-operator") }}Cluster{{ end }}Role
metadata:
  name: mysql-operator
  namespace: {{ .Values.resources.namespace }}
  labels:
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs:
    - get
    - list
    - patch
    - update
    - watch

  - apiGroups: [""]
    resources: ["secrets"]
    verbs:
      {{- if hasPrefix "0.1" .Values.operator.image.tag }}
      - get
      {{- end}}
      - create

  - apiGroups: [""]
    resources:
    - services
    {{- if hasPrefix "0.1" .Values.operator.image.tag }}
    - configmaps
    {{- end }}
    verbs:
    - create
    - get
    - list
    - watch

  - apiGroups: [""]
    resources: ["events"]
    verbs:
    - create
    - update
    - patch

  - apiGroups: ["apps"]
    resources: ["statefulsets"]
    verbs:
    - create
    - get
    - list
    - patch
    - update
    - watch

  - apiGroups: ["mysql.oracle.com"]
    resources:
    - mysqlbackups
    - mysqlbackupschedules
    - mysqlclusters
    - mysqlclusters/finalizers
    - mysqlrestores
    verbs:
    - get
    - list
    - patch
    - update
    - watch

  - apiGroups: ["mysql.oracle.com"]
    resources: ["mysqlbackups"]
    verbs: ["create"]

---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: {{ if and (.Values.operator.global) (eq .Values.resources.namespace "mysql-operator") }}Cluster{{ end }}Role
metadata:
  name: mysql-agent
  namespace: {{ .Values.resources.namespace }}
  labels:
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs:
    - get
    - list
    - patch
    - update
    - watch

  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get"]

  - apiGroups: [""]
    resources: ["events"]
    verbs:
    - create
    - update
    - patch

  - apiGroups: ["mysql.oracle.com"]
    resources:
    - mysqlbackups
    - mysqlbackupschedules
    - mysqlclusters
    - mysqlclusters/finalizers
    - mysqlrestores
    verbs:
    - get
    - list
    - patch
    - update
    - watch

---

apiVersion: rbac.authorization.k8s.io/v1
kind: {{ if and (.Values.operator.global) (eq .Values.resources.namespace "mysql-operator") }}Cluster{{ end }}Role
metadata:
  name: {{ .Values.resources.rbacName }}
  namespace: {{ .Values.resources.namespace }}
  labels:
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'

---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind:  {{ if and (.Values.operator.global) (eq .Values.resources.namespace "mysql-operator") }}Cluster{{ end }}RoleBinding
metadata:
  name: mysql-operator
  namespace: {{ .Values.resources.namespace }}
  labels:
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind:  {{ if and (.Values.operator.global) (eq .Values.resources.namespace "mysql-operator") }}Cluster{{ end }}Role
  name: mysql-operator
subjects:
- kind: ServiceAccount
  name: mysql-operator
  namespace: {{ .Values.resources.namespace }}

---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind:  {{ if and (.Values.operator.global) (eq .Values.resources.namespace "mysql-operator") }}Cluster{{ end }}RoleBinding
metadata:
  name: mysql-agent
  namespace: {{ .Values.resources.namespace }}
  labels:
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind:  {{ if and (.Values.operator.global) (eq .Values.resources.namespace "mysql-operator") }}Cluster{{ end }}Role
  name: mysql-agent
subjects:
- kind: ServiceAccount
  name: mysql-agent
  namespace: {{ .Values.resources.namespace }}

---

apiVersion: rbac.authorization.k8s.io/v1
kind:  {{ if and (.Values.operator.global) (eq .Values.resources.namespace "mysql-operator") }}Cluster{{ end }}RoleBinding
metadata:
  name: {{ .Values.resources.rbacName }}
  namespace: {{ .Values.resources.namespace }}
  labels:
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
roleRef:
  kind: {{ if and (.Values.operator.global) (eq .Values.resources.namespace "mysql-operator") }}Cluster{{ end }}Role
  name: mysql-resources
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: Group
  name: system:serviceaccounts
  apiGroup: rbac.authorization.k8s.io
  namespace: {{ .Values.resources.namespace }}


