apiVersion: mysql.oracle.com/v1alpha1
kind: Cluster
metadata:
  name: {{.Values.innodb.clusterName}}
  namespace: {{.Values.operator.namespace}}
  annotations:
   "helm.sh/hook": "post-install"
   "helm.sh/hook-weight": "10"
spec:
  members: {{.Values.innodb.replicas}}
  rootPasswordSecret: 
    name: root-password
  version: {{.Values.innodb.version}}           
  config:                                
    name: innodb-mycnf
  volumeClaimTemplate:
    metadata:
      name: pvcdata
    spec:
      storageClassName: {{.Values.innodb.storageclass}}
      accessModes:
        - {{.Values.innodb.pvAccess}}
      resources:
        requests:
          storage: 20Gi
  backupVolumeClaimTemplate:
    metadata:
      name: pvcbackup
    spec:
      storageClassName: {{.Values.innodb.storageclass}}
      accessModes:
        - {{.Values.innodb.pvAccess}}
      resources:
        requests:
          storage: 20Gi

