apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-router
  namespace: {{ .Values.resources.namespace }}
  labels:
    app: mysql-router
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
  annotations:
    "helm.sh/hook": "{{ .Values.hooks.lastPriority }}"
    "helm.sh/hook-weight": "15"
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: mysql-router
  template:
    metadata:
      labels:
        app: mysql-router
    spec:
      serviceAccountName: {{ .Values.resources.rbacName }}
      containers:
      - name: mysqlrouter
        image: {{ .Values.router.image.repository }}:{{ .Values.router.image.tag }}
        env:
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.innodb.rootUser.secretName }}
              key: password
        - name: MYSQL_USER
          value: root
        - name: MYSQL_PORT
          value: "3306"
        - name: MYSQL_HOST
          value: {{ .Values.innodb.clusterName }}-0.{{ .Values.innodb.clusterName }}
        - name: MYSQL_INNODB_NUM_MEMBERS
          value: "{{ .Values.innodb.replicas }}"
        command:
        - "/bin/bash"
        - "-cx"
        - "exec /run.sh mysqlrouter"
        ports:
        - containerPort: 6446
          containerPort: 6447

---

apiVersion: v1
kind: Service
metadata:
  name: mysql-router
  namespace: {{ .Values.resources.namespace }}
  labels:
    app: mysql-router
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
spec:
  ports:
    - port: 3306
      targetPort: 6446
      protocol: TCP
      name: 3306-tcp
    - port: 3307
      targetPort: 6447
      protocol: TCP
      name: 3307-tcp
  selector:
    app: mysql-router
  type: {{ .Values.router.serviceType }}

